### PR TITLE
fix(toggle): sync initial internal toggle group state when toggle con…

### LINKED ISSUE #408: Toggle group not showing initial form control value
### Please provide the environment you discovered this bug in.

Angular: 18.2
@spartan-ng/ui-tooltip-brain: "0.0.1-alpha.356"

### Which area/package is the issue in?

toggle

### Description

Hi, I have encountered an error with the toggle group, if I set the initial form value it is not shown in a group of toggles until the user changes the choice.

I think that the issue is caused by the fact that, the toggle are not yet rendered and hence `_setSelectionByValue` exits and later when the toggles appear on `ngAfterContentInit` their state is not updated. 

It could also be possible to set the toggle state in a `BrnToggleDirective` constructor from the injected `ToggleGroupProvider`.

I have found a workaround of setting state via the toggle state input, but would like to fix this properly in a group implementation

### Please provide the exception or error you saw

_No response_

### Other information

_No response_

### I would be willing to submit a PR to fix this issue

- [X] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by goetzrobin**
…tent children become available

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our
      guidelines: https://github.com/goetzrobin/spartan/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Which package are you modifying?

- [ ] accordion
- [ ] alert
- [ ] alert-dialog
- [ ] aspect-ratio
- [ ] avatar
- [ ] badge
- [ ] button
- [ ] calendar
- [ ] card
- [ ] checkbox
- [ ] collapsible
- [ ] combobox
- [ ] command
- [ ] context-menu
- [ ] data-table
- [ ] date-picker
- [ ] dialog
- [ ] dropdown-menu
- [ ] hover-card
- [ ] icon
- [ ] input
- [ ] label
- [ ] menubar
- [ ] navigation-menu
- [ ] pagination
- [ ] popover
- [ ] progress
- [ ] radio-group
- [ ] scroll-area
- [ ] select
- [ ] separator
- [ ] sheet
- [ ] skeleton
- [ ] slider
- [ ] sonner
- [ ] spinner
- [ ] switch
- [ ] table
- [ ] tabs
- [ ] textarea
- [ ] toast
- [x] toggle
- [ ] tooltip
- [ ] typography

## What is the current behavior?

initial value set from form was not reflected in UI

Closes #408

## What is the new behavior?

toggles are in sync from the start 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: libs/ui/toggle/brain/src/lib/brn-toggle-group.component.ts [hunk 1]
```diff
@@ -89,6 +90,12 @@ export class BrnToggleGroupComponent<T = unknown> implements ControlValueAccesso
 	/** The toggles within the group. */
 	private readonly _toggleButtons = contentChildren(BrnToggleDirective, { descendants: true });
 
+	ngAfterViewInit() {
+		// This is needed because we need access to our toggles through
+		// contentChildren to sync initial values set in writeValue before they are available, e.g. default values in a form
+		this.updateSelectionState();
```
Comment (elite-benni) [inline libs/ui/toggle/brain/src/lib/brn-toggle-group.component.ts:96]: I don't like the imperative calls to this update function. 
I think I found a solution to this problem, which makes the toggle components even cleaner.
One downside is, that the state of the brn-toggle is more coupled to the group when inside a toggle-group.
I added a draft PR #484 LMKWYT
