### PR TITLE
fix(command): add valueChanged again

### LINKED ISSUE #589: command: valueChanged does not exist anymore
### Please provide the environment you discovered this bug in.

this is a regression since the rework of the command component.

### Which area/package is the issue in?

command

### Description

The previous implementation exposed the valueChanged output. 
The new implementation is missing this feature. 

### Please provide the exception or error you saw

```true

```

### Other information

_No response_

### I would be willing to submit a PR to fix this issue

- [x] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by elite-benni**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our
      guidelines: https://github.com/goetzrobin/spartan/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Which package are you modifying?

- [ ] accordion
- [ ] alert
- [ ] alert-dialog
- [ ] aspect-ratio
- [ ] avatar
- [ ] badge
- [ ] button
- [ ] calendar
- [ ] card
- [ ] checkbox
- [ ] collapsible
- [ ] combobox
- [x] command
- [ ] context-menu
- [ ] data-table
- [ ] date-picker
- [ ] dialog
- [ ] dropdown-menu
- [ ] hover-card
- [ ] icon
- [ ] input
- [ ] label
- [ ] menubar
- [ ] navigation-menu
- [ ] pagination
- [ ] popover
- [ ] progress
- [ ] radio-group
- [ ] scroll-area
- [ ] select
- [ ] separator
- [ ] sheet
- [ ] skeleton
- [ ] slider
- [ ] sonner
- [ ] spinner
- [ ] switch
- [ ] table
- [ ] tabs
- [ ] textarea
- [ ] toast
- [ ] toggle
- [ ] tooltip
- [ ] typography

## What is the current behavior?

valueChanged Event does not exist anymore, but it was implemented in the cmdk version. 

Closes #589 

## What is the new behavior?

``valueChanged`` was added and returns the value of the active item. 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

**Review by thatsamsonkid — APPROVED** [review]
LGTM!

File: libs/brain/command/src/lib/brn-command.directive.ts [hunk 1]
```diff
@@ -42,6 +45,9 @@ export class BrnCommandDirective implements AfterViewInit {
 	/** A custom filter function to use when searching. */
 	public readonly filter = input<CommandFilter>(this._defaultFilter);
 
+	/** when the selection has changed */
+	public readonly valueChanged = output<string>();
```
Comment (ashley-hunter) [inline libs/brain/command/src/lib/brn-command.directive.ts:49]: I realize this is to match the previous implementation API, but I wonder might it be good to call this `valueChange` instead? This aligns with our other similarly named outputs and it would follow Angular's convention for two way binding should we ever want to add a `value` input in future?

I don't mind retaining the same naming as before if we feel it is preferable, but just wanted to gather thoughts on it.

File: libs/brain/command/src/lib/brn-command.directive.ts [hunk 2]
```diff
@@ -76,6 +82,13 @@ export class BrnCommandDirective implements AfterViewInit {
 			},
 			{ allowSignalWrites: true },
 		);
+
+		this.keyManager.change.pipe(takeUntilDestroyed()).subscribe(() => {
+			const value = (this.keyManager.activeItem as BrnCommandItemDirective)?.value();
```
Comment (ashley-hunter) [inline libs/brain/command/src/lib/brn-command.directive.ts:87]: I think this casting can be removed as the type or `BrnCommandItemDirective | null` is inferred and we are handling the null case with `?`:

```suggestion
    const value = this.keyManager.activeItem?.value();
```

**Review by ashley-hunter — APPROVED** [review]
Looks good, just had a thought about the name, interested to hear thoughts!

File: libs/brain/command/src/lib/brn-command.directive.ts (hunk 2 above)
Comment (elite-benni) [reply libs/brain/command/src/lib/brn-command.directive.ts:87]: you are right, thanks for pointing that out

File: libs/brain/command/src/lib/brn-command.directive.ts (hunk 1 above)
Comment (elite-benni) [reply libs/brain/command/src/lib/brn-command.directive.ts:49]: If we can change the naming, now is the best time.
I did not think about it, but I think it is the better naming!
