### PR TITLE
fix: rewrite checkbox to use button instead of input

### LINKED ISSUE #644: Checkbox - Accessibility Issue in brn-checkbox Component
### Please provide the environment you discovered this bug in.

"@angular/core": "18.2.10"
"@spartan-ng/brain": "0.0.1-alpha.404"

### Which area/package is the issue in?

checkbox

### Description

The brn-checkbox component is failing accessibility tests due to improper implementation of ARIA attributes.

**Issue Description**
When running accessibility tests on the checkbox component, the following error is reported:
`'aria-conditional-attr' | 'serious' | "Ensure ARIA attributes are used as described in the specification of the element's role"`

**Root Cause**
The input element in the checkbox component has conflicting role and state management attributes:

1. Native <input type="checkbox"> is being used
2. Redundant explicit role="checkbox" is added
3. Using aria-checked="true" instead of the native checked attribute.

`<input tabindex="-1" type="checkbox" role="checkbox" value="on" id="default-checkbox" name="default-checkbox" aria-label="Default Checkbox" aria-checked="true" style="position: absolute; width: 1px; height: 1px; padding: 0px; margin: -1px; overflow: hidden; clip: rect(0px, 0px, 0px, 0px); white-space: nowrap; border-width: 0px;">`

**Expected Behavior**
The checkbox should comply with ARIA specifications, which state that when using native HTML elements, their implicit roles should be relied upon rather than explicitly declared, and their native state attributes should be used instead of ARIA equivalents when available.

### Please provide the exception or error you saw

```true
`'aria-conditional-attr' | 'serious' | "Ensure ARIA attributes are used as described in the specification of the element's role"`
```

### Other information

_No response_

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [x] No

### PR DESCRIPTION
**Pull request by goetzrobin**
I switched the underlying implementation from a hidden input to a button. similar to the switch primitive. this fixes some a11y issues that occured with the previous implementation.

closes #644

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our
      guidelines: https://github.com/goetzrobin/spartan/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Which package are you modifying?

- [ ] accordion
- [ ] alert
- [ ] alert-dialog
- [ ] aspect-ratio
- [ ] avatar
- [ ] badge
- [ ] breadcrumb
- [ ] button
- [ ] calendar
- [ ] card
- [ ] carousel
- [x] checkbox
- [ ] collapsible
- [ ] combobox
- [ ] command
- [ ] context-menu
- [ ] data-table
- [ ] date-picker
- [ ] dialog
- [ ] dropdown-menu
- [ ] form-field
- [ ] hover-card
- [ ] icon
- [ ] input
- [ ] input-otp
- [ ] label
- [ ] menubar
- [ ] navigation-menu
- [ ] pagination
- [ ] popover
- [ ] progress
- [ ] radio-group
- [ ] scroll-area
- [ ] select
- [ ] separator
- [ ] sheet
- [ ] skeleton
- [ ] slider
- [ ] sonner
- [ ] spinner
- [ ] switch
- [ ] table
- [ ] tabs
- [ ] textarea
- [ ] toast
- [ ] toggle
- [ ] toggle-group
- [ ] tooltip
- [ ] typography

## What is the current behavior?

Closes #644, #324

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### CODE REVIEW

File: libs/brain/checkbox/src/lib/brn-checkbox.component.ts [hunk 1]
```diff
@@ -30,72 +33,62 @@ export const BRN_CHECKBOX_VALUE_ACCESSOR = {
...
 		'[attr.data-disabled]': 'state().disabled()',
-		'[attr.aria-labelledby]': 'null',
-		'[attr.aria-label]': 'null',
-		'[attr.aria-describedby]': 'null',
-		'[attr.id]': 'hostId()',
-		'[attr.name]': 'hostName()',
 	},
 	providers: [BRN_CHECKBOX_VALUE_ACCESSOR],
 	changeDetection: ChangeDetectionStrategy.OnPush,
 	encapsulation: ViewEncapsulation.None,
```
Comment (ashley-hunter) [inline libs/brain/checkbox/src/lib/brn-checkbox.component.ts:79]: I think this can be removed here as this component has no styles.

**Review by ashley-hunter — APPROVED** [review]
Thanks! A great update, really simplifies things! I left a few comments on things - none of which you actually changed, but just "tidy" up things in this area - but they can be done in a separate PR if you'd rather.

I noticed this example is still present but isn't relevant any more as we removed this input a while back.

image

File: libs/brain/checkbox/src/lib/brn-checkbox.component.ts (hunk 1 above)
Comment (goetzrobin) [reply libs/brain/checkbox/src/lib/brn-checkbox.component.ts:79]: I will check it out. I thought this was necessary to "redirect: the aria-label and aria-describedby inputs to the child, but I could be wrong

Comment (ashley-hunter) [reply libs/brain/checkbox/src/lib/brn-checkbox.component.ts:79]: Hmm, GitHub seems to have highlighted different lines than I selected, I was only referring to the view encapsulation line, the rest are perfect 😊

Comment (goetzrobin) [reply libs/brain/checkbox/src/lib/brn-checkbox.component.ts:79]: That makes perfect sense! I'll remove it!

**Review by ashley-hunter — APPROVED** [review]
Looks great, thank you for the updates! Big improvement!
