### PR TITLE
fix(switch): fix accessibility issues

### LINKED ISSUE #648: Switch - Accessibility issue of placement of `role: switch`
### Please provide the environment you discovered this bug in.

"@angular/core": "18.2.10"
"@spartan-ng/brain": "0.0.1-alpha.404"

### Which area/package is the issue in?

switch

### Description

switch

### Please provide the exception or error you saw

```true
The brn-switch component is misconfigured in terms of accessibility, resulting in inability to test the component effectively.

Specifically, the matcher test matcher of `getByRole('switch')` is unable to be used due to the role of `switch` being placed in a nested <input> (see https://github.com/spartan-ng/spartan/blob/main/libs/brain/switch/src/lib/brn-switch.component.ts#L47).

Doing a `getByRole('switch').click()` does not actually toggle the switch. In order to fix this, the `role` of `switch` should be on the actual `brn-switch` component. Thanks!
```

### Other information

_No response_

### I would be willing to submit a PR to fix this issue

- [ ] Yes
- [x] No

### PR DESCRIPTION
**Pull request by goetzrobin**
putting the role in the right place
association aria and data attributes with the container using native attributes (checked,required,disabled) on hidden input

here is where it gets fun:
identified issue where checked is not applied correctly and found this gem: https://github.com/angular/components/issues/26101 current approach uses preventDefault in toggle and breaks. this current version works but not if we click on the switch (background) and not the thumb what's even more fun: e2e tests pass because cypress clicks right in the middle where our thumb is.

open to suggestions and help!

fixes #648

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our
      guidelines: https://github.com/goetzrobin/spartan/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

## Which package are you modifying?

- [ ] accordion
- [ ] alert
- [ ] alert-dialog
- [ ] aspect-ratio
- [ ] avatar
- [ ] badge
- [ ] button
- [ ] calendar
- [ ] card
- [ ] carousel
- [ ] checkbox
- [ ] collapsible
- [ ] combobox
- [ ] command
- [ ] context-menu
- [ ] data-table
- [ ] date-picker
- [ ] dialog
- [ ] dropdown-menu
- [ ] hover-card
- [ ] icon
- [ ] input
- [ ] input-otp
- [ ] label
- [ ] menubar
- [ ] navigation-menu
- [ ] pagination
- [ ] popover
- [ ] progress
- [ ] radio-group
- [ ] scroll-area
- [ ] select
- [ ] separator
- [ ] sheet
- [ ] skeleton
- [ ] slider
- [ ] sonner
- [ ] spinner
- [x] switch
- [ ] table
- [ ] tabs
- [ ] textarea
- [ ] toast
- [ ] toggle
- [ ] toggle-group
- [ ] tooltip
- [ ] typography

## What is the current behavior?

Closes #648

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

## Other information

HELP. PLEASE

### CODE REVIEW

**Comment by ashley-hunter** [comment]
Could you elaborate on what exactly the issue is when `preventDefault` is used? I notice clicking on the switch background does not work in some cases, but when I add the following to the `host:` property:

```ts
'(click)': 'toggle(); $event.preventDefault()',
```

That does appear to resolve the issue - am I missing something else?

I guess an alternative would be to evaluate if the `input` element is required at all? For example, Material does not include one in their implementation:

https://github.com/angular/components/blob/0e391700cb55786a74a3aa16757e90596eb55e6c/src/material/slide-toggle/slide-toggle.html

**Comment by goetzrobin** [comment]
Yeah sorry I should have been more specific.

If you inspect the input element in your browser you will see that adding $event.preventDefault() messes with the checked attribute being applied to the input element.

It's not applied correctly once you add that line. The behavior is described in the linked issue in the PR, which has a stackblitz that shows this behavior also!

Does that help? 
Interesting to see that they are using a button. Do you think that's a better way to go about it?

**Comment by ashley-hunter** [comment]
Yes, binding to `[attr.checked]` instead of `[checked]` seems to resolve the issue for me.

**Comment by goetzrobin** [comment]
> Yes, binding to `[attr.checked]` instead of `[checked]` seems to resolve the issue for me.

Is that with the $event.preventDefault()? That would be a lovely fix!

**Comment by ashley-hunter** [comment]
Yes 😊 that is with preventDefault. Seems to work, but if I have missed anything I'm happy to look again.

File: libs/brain/switch/src/lib/brn-switch.component.ts [hunk 1]
```diff
@@ -36,48 +35,46 @@ export const BRN_SWITCH_VALUE_ACCESSOR = {
 
 const CONTAINER_POST_FIX = '-switch';
 
+let uniqueIdCounter = 0;
+
 @Component({
 	selector: 'brn-switch',
-	imports: [NgStyle],
+	standalone: true,
```
Comment (ashley-hunter) [inline libs/brain/switch/src/lib/brn-switch.component.ts:42]: I think this can be removed now that we target Angular v19+ this is the default.

File: libs/brain/switch/src/lib/brn-switch.component.ts [hunk 2]
```diff
@@ -36,48 +35,46 @@ export const BRN_SWITCH_VALUE_ACCESSOR = {
...
-		<ng-content select="brn-switch-thumb" />
+			[attr.aria-checked]="checked()"
+			[attr.aria-label]="ariaLabel() || null"
+			[attr.aria-labelledby]="mutableAriaLabelledby()() || null"
+			[attr.aria-describedby]="ariaDescribedby() || null"
+			[attr.data-state]="checked() ? 'checked' : 'unchecked'"
+			[attr.data-focus-visible]="focusVisible()"
+			[attr.data-focus]="focused()"
+			[attr.data-disabled]="state().disabled()"
+			[disabled]="disabled()"
```
Comment (ashley-hunter) [inline libs/brain/switch/src/lib/brn-switch.component.ts:60]: I think this should also use the disabled state signal.

```suggestion
			[disabled]="state().disabled()"
```

File: libs/brain/switch/src/lib/brn-switch.component.ts [hunk 3]
```diff
@@ -141,33 +175,23 @@ export class BrnSwitchComponent implements AfterContentInit, OnDestroy {
...
-			const label = parent?.querySelector(`label[for="${this.forChild(this.state().id)}"]`);
-			if (!label) return;
-			this._renderer.setAttribute(label, 'data-disabled', this.state().disabled() ? 'true' : 'false');
+			const isDisabled = this.state().disabled();
+			const state = this.state();
+			if (!this._elementRef.nativeElement || !this._isBrowser) return;
+
+			const switchElement = this._elementRef.nativeElement;
+
+			const labelElement = this._findLabelForSwitch(switchElement);
```
Comment (ashley-hunter) [inline libs/brain/switch/src/lib/brn-switch.component.ts:184]: Rather than needing this `_findLabelForSwitch` method, could we just use `this._elementRef.nativeElement.closest('label')` to search the parents for a label?

**Review by ashley-hunter — CHANGES_REQUESTED** [review]
Thanks! Looks great and works well! I agree, I think removing the input is probably the best option! Had a few very small suggestions, but really nice improvement!

**Review by ashley-hunter — APPROVED** [review]
Looks great, thank you!
