### PR TITLE
Fix generator

### LINKED ISSUE #852: Error when generating components using buildable true and generateAs entrypoint
The following options work fine in an existing and new project

```json
{
  "componentsPath": "libs/ui",
  "buildable": false,
  "generateAs": "entrypoint"
}
```

When I try to generate components with `buildable: true` the following error is printed in the terminal.

```
npx nx g @spartan-ng/cli:ui

 NX  Generating @spartan-ng/cli:ui

Configuration file not found, creating a new one...
✔ Choose a directory to place your spartan libraries, e.g. libs/ui · libs/ui
✔ Should the libraries be buildable? (Y/n) · true
✔ How should we generate the components? · entrypoint
? Choose which primitives you want to copy … 
? Choose which primitives you want to copy … 
? Choose which primitives you want to copy … 
✔ Choose which primitives you want to copy · accordion
The "--simpleName" option is deprecated and will be removed in Nx 22. Please use the "--name" option to provide the exact name you want for the library.

 NX   The folder for the secondary entry point "libs/ui/accordion" already exists.

Pass --verbose to see the stacktrace.
```
The error occurs in an existing nx (21.3) project, but the libs/ui folder are delete. It also happens in an new nx (21.4) project without a libs directory at all. When i change the directory to `test-ui` the error persists. (` NX   The folder for the secondary entry point "libs/test-ui/accordion" already exists.`)

_Originally posted by @marcjulian in https://github.com/spartan-ng/spartan/issues/814#issuecomment-3206252522_

### PR DESCRIPTION
**Pull request by MerlinMoos**
## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our
      guidelines: https://github.com/spartan-ng/spartan/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

### Primitives

- [ ] accordion
- [ ] alert
- [ ] alert-dialog
- [ ] aspect-ratio
- [ ] avatar
- [ ] badge
- [ ] breadcrumb
- [ ] button
- [ ] calendar
- [ ] card
- [ ] carousel
- [ ] checkbox
- [ ] collapsible
- [ ] combobox
- [ ] command
- [ ] context-menu
- [ ] data-table
- [ ] date-picker
- [ ] dialog
- [ ] dropdown-menu
- [ ] form-field
- [ ] hover-card
- [ ] icon
- [ ] input
- [ ] input-otp
- [ ] label
- [ ] menubar
- [ ] navigation-menu
- [ ] pagination
- [ ] popover
- [ ] progress
- [ ] radio-group
- [ ] scroll-area
- [ ] select
- [ ] separator
- [ ] sheet
- [ ] skeleton
- [ ] slider
- [ ] sonner
- [ ] spinner
- [ ] switch
- [ ] table
- [ ] tabs
- [ ] textarea
- [ ] toggle
- [ ] toggle-group
- [ ] tooltip
- [ ] typography

### Others

- [ ] trpc
- [ ] nx
- [ ] repo
- [x] cli

## What is the current behavior?

fix the generation of buldable entrypoints

Closes #852 

## Does this PR introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: libs/cli/src/generators/base/generator.ts [hunk 1]
```diff
@@ -49,6 +48,7 @@ async function generateEntrypointFiles(tree: Tree, alias: string, options: HlmBa
 			json.compilerOptions.paths[alias] = [`./${joinPathFragments(targetLibDir, 'index.ts').replace(/\\/g, '/')}`];
 			return json;
 		});
+		generateFiles(tree, path.join(__dirname, '..', 'ui', 'libs', options.internalName, 'files'), targetLibDir, options);
```
Comment (marcjulian) [inline libs/cli/src/generators/base/generator.ts]: Error is gone, but buildable entry points don't have the ui component files copied over. I moved this below the if statement and now the files are copied for (non)-buildable

**Comment by MerlinMoos** [comment]
Thanks, i will quick fix the pipeline and the @goetzrobin can merge it
