### PR TITLE
fix(select): voiceover navigatability and typehead restored

### LINKED ISSUE #773: select: not navigatable with VO screenreader
### Please provide the environment you discovered this bug in.

Latest prod version

This may not be limited to Voiceover, it could be an issue with Jaws/NVDA but would need to check and or if someone else could verify that.

### Which area/package is the issue in?

select

### Description

When trying to navigate the Select component with just the keyboard with Voiceover, the select dropdown opens fine and VO reads the first option but from there the down arrow does not take you to the next option, instead VO simply re-reads the same option and then the up arrow seems to randomly take me outside of the select dropdown list (in my case it jumped to my browser bookmarks section). 

Keyboard navigation works fine without Voiceover, i think unfortunately it's some weirdness with the way VO is handling active descendant and I believe it simply doesnt like that we have an intermediate div element between the element that has the activedescendant and listbox role and the actual list. Idk if that's the only issue, in some research I found VO and active descendant in safari can be an issue but not sure if that's old news or not. The radix select works fine and we have a very similar html structure but I believe they rely on the tab-index focus strategy for the listbox.

### Please provide the exception or error you saw

```true

```

### Other information

_No response_

### I would be willing to submit a PR to fix this issue

- [x] Yes
- [ ] No

### PR DESCRIPTION
**Pull request by thatsamsonkid**
- fix focus styling

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our
      guidelines: https://github.com/spartan-ng/spartan/blob/main/CONTRIBUTING.md#-commit-message-guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

- [x] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, local variables)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] CI related changes
- [ ] Documentation content changes
- [ ] Other... Please describe:

### Primitives

- [ ] accordion
- [ ] alert
- [ ] alert-dialog
- [ ] aspect-ratio
- [ ] avatar
- [ ] badge
- [ ] breadcrumb
- [ ] button
- [ ] calendar
- [ ] card
- [ ] carousel
- [ ] checkbox
- [ ] collapsible
- [ ] combobox
- [ ] command
- [ ] context-menu
- [ ] data-table
- [ ] date-picker
- [ ] dialog
- [ ] dropdown-menu
- [ ] form-field
- [ ] hover-card
- [ ] icon
- [ ] input
- [ ] input-otp
- [ ] label
- [ ] menubar
- [ ] navigation-menu
- [ ] pagination
- [ ] popover
- [ ] progress
- [ ] radio-group
- [ ] scroll-area
- [x] select
- [ ] separator
- [ ] sheet
- [ ] skeleton
- [ ] slider
- [ ] sonner
- [ ] spinner
- [ ] switch
- [ ] table
- [ ] tabs
- [ ] textarea
- [ ] toggle
- [ ] toggle-group
- [ ] tooltip
- [ ] typography

### Others

- [ ] trpc
- [ ] nx
- [ ] repo
- [ ] cli

## What is the current behavior?

Closes #773 

## Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

Not sure if we consider the outline change a breaking change? Might mess with peoples styles?

### CODE REVIEW

**Comment by thatsamsonkid** [comment]
Ok I confirmed this is working as expected with Windows + NVDA and on Mac

File: libs/brain/select/src/lib/brn-select-content.ts [hunk 1]
```diff
@@ -170,33 +167,39 @@ export class BrnSelectContent<T> implements AfterContentInit {
 	}
 
 	ngAfterContentInit(): void {
-		this.keyManager = new ActiveDescendantKeyManager(this._options, this._injector)
+		this.keyManager = new FocusKeyManager(this._options())
```
Comment (ashley-hunter) [inline libs/brain/select/src/lib/brn-select-content.ts]: The focus key manager now allows a signal to be passed directly for the options ensuring things stay updated if the options change, we just need to also pass the injector.

```suggestion
		this.keyManager = new FocusKeyManager(this._options, this._injector)
```

**Review by ashley-hunter — APPROVED** [review]
Looks good to me! Had one small suggestion - but its just a nice to have 😊

File: libs/brain/select/src/lib/brn-select-content.ts (hunk 1 above)
Comment (thatsamsonkid) [reply libs/brain/select/src/lib/brn-select-content.ts]: @ashley-hunter - thanks for this, I wasn't aware. I'll update it!
